site_name: pictures-manager
repo_url: https://github.com/edouardbruelhart/pictures-manager
site_url: https://edouardbruelhart.github.io/pictures-manager
site_description: An automated process to format pictures from field collection in order to import them to iNaturalist.
site_author: Edouard Brülhart
edit_uri: edit/main/docs/
repo_name: edouardbruelhart/pictures-manager
copyright: Maintained by <a href="https://edouardbruelhart.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/edouardbruelhart/pictures-manager
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pictures-manager

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
